jury/__init__.py

- Releasing v0.0.6
Renamings, updates in the test scripts and dependency packages.

Release v0.0.6

---

README.md
jury/core.py

README.md updated (blog-post and badges).

---

examples/environment.yml
examples/jury_evaluate.ipynb

Jury example notebook added with environment.yml update.

---

jury/core.py
jury/metrics/_base.py
jury/metrics/bertscore.py
jury/metrics/bleu.py
jury/metrics/sacrebleu.py
jury/metrics/squad.py
tests/jury/metrics/test_bleu.py
tests/jury/metrics/test_sacrebleu.py
tests/jury/test_jury.py

- Bleu inputs for single prediction and multiple references case is added to related metric's preprocess functions. (bleu, sacrebleu).
- Test cases updated accordingly.

Bleu input cases handled in compute function.

---

README.md
jury/__init__.py
jury/cli.py
jury/core.py
tests/jury/test_cli.py
tests/test_data/predictions.txt
tests/test_data/references.txt
tests/utils.py

Closes: #14.
CLI Implementation has been completed. With a new implementation a score result can be obtained by `jury eval --args`.

Cli implementation

---

jury/core.py
tests/jury/conftest.py
tests/jury/test_jury.py
tests/test_data/expected_outputs/metrics/test_accuracy.json
tests/test_data/expected_outputs/metrics/test_bertscore.json
tests/test_data/expected_outputs/metrics/test_bleu.json
tests/test_data/expected_outputs/metrics/test_f1.json
tests/test_data/expected_outputs/metrics/test_meteor.json
tests/test_data/expected_outputs/metrics/test_precision.json
tests/test_data/expected_outputs/metrics/test_recall.json
tests/test_data/expected_outputs/metrics/test_rouge.json
tests/test_data/expected_outputs/metrics/test_sacrebleu.json
tests/test_data/expected_outputs/metrics/test_seqeval.json
tests/test_data/expected_outputs/metrics/test_squad.json
tests/test_data/expected_outputs/test_cli.json
tests/test_data/expected_outputs/test_jury.json

Handle for empty predictions & references on Jury (skipping empty).

---

jury/__init__.py
jury/core.py

Bug fix: Typo corrected in _remove_empty() in core.py.

---

examples/jury_evaluate.ipynb
jury/core.py
jury/definitions.py
jury/metrics/_core/auto.py
jury/metrics/_core/auxiliary.py
jury/metrics/_core/utils.py
jury/metrics/bertscore/bertscore_for_language_generation.py
jury/metrics/bleu/bleu.py
jury/metrics/sacrebleu/sacrebleu_for_language_generation.py
jury/metrics/seqeval/seqeval_for_sequence_classification.py
jury/utils/common.py
requirements.txt
tests/jury/conftest.py
tests/jury/metrics/test_custom_bleu.py
tests/test_data/custom_bleu/__init__.py
tests/test_data/custom_bleu/custom_bleu.py
tests/test_data/custom_bleu/custom_bleu_for_language_generation.py
tests/test_data/expected_outputs/metrics/test_custom_bleu.json

Fixes #68 
- `metric_name` argument changed as `path`.
- Both relative and absolute paths are available for use.

Metric name path bug fix.

---

jury/metrics/_core/auto.py
jury/metrics/bleurt/__init__.py
jury/metrics/bleurt/bleurt.py
jury/metrics/bleurt/bleurt_for_language_generation.py
jury/metrics/seqeval/seqeval_for_sequence_classification.py
setup.py
tests/jury/metrics/test_bleurt.py
tests/test_data/expected_outputs/metrics/test_bleurt.json

Added BLEURT.

---

README.md

Closes #80
Added DOI badge and citation information.

README.md updated with doi badge and citation inforamtion.

---

jury/metrics/accuracy/accuracy_for_sequence_classification.py
jury/metrics/bleu/bleu_for_language_generation.py
jury/metrics/prism/prism_for_language_generation.py
jury/metrics/squad/squad_for_language_generation.py
setup.py
tests/test_data/custom_bleu/custom_bleu_for_language_generation.py

Dl manager rework

---

jury/metrics/meteor/meteor_for_language_generation.py
requirements.txt
setup.py

Nltk upgrade

---

jury/metrics/__init__.py
jury/metrics/cer/__init__.py
jury/metrics/cer/cer.py
jury/metrics/cer/cer_for_language_generation.py
setup.py
tests/jury/metrics/test_cer.py
tests/test_data/expected_outputs/metrics/test_cer.json

CER metric implementation.

---

tests/jury/conftest.py
tests/jury/metrics/test_accuracy.py
tests/jury/metrics/test_bertscore.py
tests/jury/metrics/test_bleu.py
tests/jury/metrics/test_bleurt.py
tests/jury/metrics/test_cer.py
tests/jury/metrics/test_custom_bleu.py
tests/jury/metrics/test_f1.py
tests/jury/metrics/test_meteor.py
tests/jury/metrics/test_precision.py
tests/jury/metrics/test_prism.py
tests/jury/metrics/test_recall.py
tests/jury/metrics/test_rouge.py
tests/jury/metrics/test_sacrebleu.py
tests/jury/metrics/test_seqeval.py
tests/jury/metrics/test_squad.py
tests/jury/test_jury.py
tests/test_data/expected_outputs/test_jury.json

- Bertscore removed from regular tests.

Test cases refactored.

---

jury/metrics/bleurt/bleurt_for_language_generation.py
jury/metrics/prism/prism_for_language_generation.py

License information added for prism and bleurt.

---

jury/core.py
jury/metrics/bleu/bleu_for_language_generation.py
jury/metrics/bleurt/bleurt.py
jury/metrics/precision/precision.py
jury/metrics/squad/squad_for_language_generation.py
jury/utils/io.py
tests/test_data/custom_bleu/custom_bleu_for_language_generation.py

Remove Unused Imports

---

jury/metrics/__init__.py
jury/metrics/wer/__init__.py
jury/metrics/wer/wer.py
jury/metrics/wer/wer_for_language_generation.py
setup.py
tests/jury/conftest.py
tests/jury/metrics/test_wer.py
tests/test_data/expected_outputs/metrics/test_wer.json
tests/test_data/expected_outputs/test_jury.json

Added WER metric.

---

jury/metrics/__init__.py
jury/metrics/chrf/__init__.py
jury/metrics/chrf/chrf.py
jury/metrics/chrf/chrf_for_language_generation.py
tests/jury/metrics/test_chrf.py
tests/test_data/expected_outputs/metrics/test_chrf.json

CHRF metric added.

---

requirements.txt

validators added to the requirements.

---

requirements-dev.txt
setup.py
tests/test_data/expected_outputs/metrics/test_cer.json
tests/test_data/expected_outputs/metrics/test_wer.json

WER & CER Test outputs corrected.
- unbabel-comet is updated to more recent version.

Intermediate patch, fixes, updates.

---

setup.py

Related issue https://github.com/PyCQA/flake8/issues/1701

`flake8` error on python3.7

---

requirements.txt
setup.py

Refactored requirements (sklearn).

---

requirements.txt
setup.py

Dependency refactor for breaking loose versions.

datasets dependency added with constraint.

---

jury/__init__.py
requirements.txt

- Version bumped to `2.2.4` (from `2.2.3`)

Package `evaluate` updated to 0.4 (from <0.3).

---

.github/workflows/ci.yml
jury/__init__.py
setup.py

Drop py3.7 support, change CI.
